name: Build and push images

on:
  workflow_dispatch:
    inputs:
      dockerhubImageName:
        description: 'dockerhub image name'
        required: true
        default: 'dtyq/php-dockerfile'
      ghcrImageName:
        description: 'ghcr.io image name'
        required: true
        default: 'ghcr.io/dtyq/php-dockerfile'
      awsEcrImageName:
        description: 'AWS ECR image name'
        required: true
        default: 'public.ecr.aws/dtyq/php-dockerfile'
  schedule:
    # every Wednesday at 3:42 AM(UTC, Beijing time: 11:42 AM)
    - cron:  '42 3 * * 3'

env:
  TRY_MIRRORS: ""
  PUBLIC_MIRROR: "https://dl-cdn.alpinelinux.org" # no mirror needed at github actions

jobs:
  prepare:
    name: Prepare matrix
    runs-on: ubuntu-latest
    outputs:
      tasks: ${{ steps.gentasks.outputs.tasks }}
    steps:
      - name: Generate tasks
        shell: python3 {0}
        id: gentasks
        run: |
          import os, json

          phpAlpineVersions = {
            "8.3": "3.20",
            "8.2": "3.20",
            "8.1": "3.19",
            "8.0": "3.16",
            "7.4": "3.15",
          }

          extVersions = [
            # swoole 5.1 branch
            "swoole-5.1.5",
            # swoole 4.8 branch
            "swoole-4.8.13",
            # swow
            "swow-1.5.3",
          ]

          extraExts = [
            "jsonpath",
            "parle",
            "xlswriter",
          ]
          extraExtTag = "-".join(sorted(extraExts))

          tags = []
          for phpVer, alpineVer in phpAlpineVersions.items():
            for ext in extVersions:
              if ext.startswith("swoole-5") and phpVer == "7.4":
                # swoole 5 不支持 PHP 7.4
                continue
              if ext.startswith("swoole-4") and phpVer == "8.3":
                # swoole 4 不支持 PHP 8.3
                continue
              if ext.startswith("swow") and phpVer == "7.4":
                # swow 不支持 PHP 7.4
                continue
              tags.append(f"{phpVer}-alpine-{alpineVer}-{ext}-{extraExtTag}")

          images = []
          images.append(f"${{ inputs.ghcrImageName }}")
          if "${{ secrets.DOCKERHUB_CRED }}":
            images.append(f"${{ inputs.dockerhubImageName }}")
          if "${{ secrets.AWS_ECR_CRED }}":
            images.append(f"${{ inputs.awsEcrImageName }}")

          serialized = json.dumps({
            "image": images,
            "tag": tags,
          })

          open(os.environ["GITHUB_OUTPUT"], "w").write(f"tasks={serialized}")

  build:
    name: Build and push images
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.tasks) }}
      max-parallel: 5
    steps:
      # checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up secrets
        shell: python3 {0}
        run: |
          import os, json, base64

          fw = open(os.path.expanduser("~/.docker/config.json"), "w")

          config = {
            "auths": {},
          }

          if "${{ matrix.image }}".startswith("ghcr.io"):
            # GHCR
            cred = base64.b64encode(b'whatever:${{ github.token }}').decode()
            config["auths"]["ghcr.io"] = {
              "auth": cred,
            }
          elif "${{ matrix.image }}".startswith("public.ecr.aws"):
            cred = "${{ secrets.AWS_ECR_CRED }}"
            if not cred:
              print("Set AWS_ECR_CRED secret in repository settings, then re-run this workflow")
              raise Exception("AWS_ECR_CRED is not set")
            config["auths"]["public.ecr.aws"] = {
              "auth": cred,
            }
          else:
            # DockerHub
            cred = "${{ secrets.DOCKERHUB_CRED }}"
            if not cred:
              print("Set DOCKERHUB_CRED secret in repository settings, then re-run this workflow")
              raise Exception("DOCKERHUB_CRED is not set")
            config["auths"]["docker.io"] = {
              "auth": cred,
            }

          fw.write(json.dumps(config))
          fw.close()

      - name: Build
        shell: bash
        run: |
          export IMAGE_NAME="${{ matrix.image }}"
          ./build.py "${{ matrix.tag }}"

